INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Aditi Khanna','Analyst',653874,'Jaipur','Y'),
	 ('Pooja Kaur','Senior Analyst',798703,'Banglore','Y'),
	 ('Kajal Mehta','Analyst',663851,'Banglore','Y'),
	 ('Amaya Joshi','Analyst',570000,'Jaipur','Y'),
	 ('Bilal Kulkarni','Associate',976125,'Jaipur','Y'),
	 ('Girish Reddy','Analyst',670531,'Pune','Y'),
	 ('Esha Dhillon','Analyst',652076,'Pune','Y'),
	 ('Kashi Nair','Analyst',655787,'Banglore','Y'),
	 ('Himanshu Dhillon','Senior Analyst',895396,'Pune','Y'),
	 ('Hetal Bhatia','Senior Analyst',820895,'Pune','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Anusha Verma','Analyst',693712,'Jaipur','Y'),
	 ('Mukta Iyer','Analyst',680229,'Banglore','Y'),
	 ('Hari Menon','Analyst',570000,'Pune','N'),
	 ('Jai Menon','Senior Associate',1704253,'Pune','Y'),
	 ('Kalpana Sharma','Analyst',669692,'Banglore','Y'),
	 ('Leena Verma','Analyst',677168,'Banglore','Y'),
	 ('Arvind Sinha','Senior Analyst',734868,'Jaipur','Y'),
	 ('Anshul Gupta','Analyst',667001,'Jaipur','Y'),
	 ('Farhan Gupta','Analyst',665610,'Pune','Y'),
	 ('Rajeshwari Joshi','Associate',1180331,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Damodar Kumar','Associate',910994,'Jaipur','Y'),
	 ('Om Sinha','Senior Analyst',846412,'Banglore','Y'),
	 ('Kunal Kaur','Analyst',570000,'Banglore','Y'),
	 ('Nishant Reddy','Senior Analyst',750000,'Banglore','N'),
	 ('Gowri Iyer','Analyst',696236,'Pune','Y'),
	 ('Akshita Verma','Analyst',570000,'Jaipur','Y'),
	 ('Renu Gupta','Senior Associate',2291090,'Banglore','Y'),
	 ('Mira Verma','Analyst',570000,'Banglore','Y'),
	 ('Chhavi Mehta','Associate',1032250,'Jaipur','Y'),
	 ('Manasi Kulkarni','Analyst',673339,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Kiran Banerjee','Analyst',699114,'Banglore','N'),
	 ('Farah Mehta','Analyst',570000,'Pune','N'),
	 ('Kala Gupta','Analyst',570000,'Banglore','Y'),
	 ('Aayush Verma','Analyst',570000,'Jaipur','Y'),
	 ('Akanksha Mehta','Analyst',695543,'Jaipur','Y'),
	 ('Lohit Reddy','Analyst',683759,'Banglore','Y'),
	 ('Jayesh Chowdhury','Analyst',570000,'Banglore','N'),
	 ('Nirmala Verma','Senior Analyst',839893,'Banglore','Y'),
	 ('Alka Reddy','Analyst',570000,'Jaipur','Y'),
	 ('Praveen Joshi','Senior Analyst',839782,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Anisha Chowdhury','Analyst',570000,'Jaipur','Y'),
	 ('Prema Khanna','Associate',1254653,'Banglore','Y'),
	 ('Pritha Sinha','Associate',1336002,'Banglore','Y'),
	 ('Karthika Joshi','Analyst',570000,'Banglore','N'),
	 ('Kalyani Patel','Analyst',570000,'Banglore','N'),
	 ('Bindiya Pillai','Associate',1098051,'Jaipur','Y'),
	 ('Annapurna Mehta','Analyst',570000,'Jaipur','Y'),
	 ('Niraj Kumar','Senior Analyst',747748,'Banglore','N'),
	 ('Nila Patel','Senior Analyst',748140,'Banglore','Y'),
	 ('Bhanu Kapoor','Senior Analyst',842482,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Poornima Mehta','Senior Analyst',738224,'Banglore','Y'),
	 ('Manju Kaur','Analyst',663969,'Banglore','Y'),
	 ('Rajesh Kapoor','Associate',1264754,'Banglore','Y'),
	 ('Kamala Kumar','Analyst',669187,'Banglore','Y'),
	 ('Reena Dhillon','Senior Associate',2452003,'Banglore','Y'),
	 ('Gayathri Kumar','Analyst',570000,'Pune','N'),
	 ('Archana Reddy','Analyst',656199,'Jaipur','Y'),
	 ('Rati Rao','Senior Associate',1915774,'Banglore','Y'),
	 ('Bala Verma','Senior Analyst',787635,'Jaipur','Y'),
	 ('Atul Bhatia','Senior Analyst',764485,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Astha Banerjee','Senior Analyst',810920,'Jaipur','Y'),
	 ('Hima Kaur','Senior Analyst',823326,'Pune','Y'),
	 ('Aarya Reddy','Analyst',668855,'Jaipur','Y'),
	 ('Ravi Bhatia','Senior Associate',2007027,'Banglore','Y'),
	 ('Jyoti Kaur','Analyst',570000,'Banglore','Y'),
	 ('Namrata Kulkarni','Analyst',694768,'Banglore','Y'),
	 ('Abhilasha Kapoor','Analyst',658651,'Jaipur','Y'),
	 ('Anmol Dhillon','Analyst',682058,'Jaipur','Y'),
	 ('Ajit Dhillon','Analyst',570000,'Jaipur','Y'),
	 ('Nishita Kapoor','Senior Analyst',812000,'Banglore','N');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Nitesh Nair','Senior Analyst',806381,'Banglore','Y'),
	 ('Arun Iyer','Senior Analyst',813200,'Jaipur','Y'),
	 ('Arjun Joshi','Senior Analyst',723808,'Jaipur','Y'),
	 ('Nitya Menon','Senior Analyst',789598,'Banglore','Y'),
	 ('Indira Kumar','Associate',907115,'Pune','Y'),
	 ('Hrithik Gupta','Senior Analyst',886891,'Pune','Y'),
	 ('Nalini Sinha','Analyst',570000,'Banglore','Y'),
	 ('Chandni Kaur','Associate',964851,'Jaipur','N'),
	 ('Avinash Dhillon','Senior Analyst',765357,'Jaipur','Y'),
	 ('Inderjit Patel','Associate',991402,'Pune','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Rani Khanna','Manager',3079338,'Banglore','Y'),
	 ('Akash Gupta','Analyst',570000,'Jaipur','Y'),
	 ('Anuj Sharma','Analyst',570000,'Jaipur','Y'),
	 ('Punit Bhatia','Associate',1093366,'Banglore','N'),
	 ('Mehul Kumar','Analyst',679372,'Banglore','Y'),
	 ('Pratyush Kapoor','Senior Analyst',882835,'Banglore','Y'),
	 ('Harshita Chowdhury','Senior Analyst',844734,'Pune','Y'),
	 ('Bhoomi Menon','Associate',974829,'Jaipur','Y'),
	 ('Manish Chowdhury','Analyst',666771,'Banglore','Y'),
	 ('Lata Sharma','Analyst',570000,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Madhuri Nair','Analyst',570000,'Banglore','Y'),
	 ('Poonam Dhillon','Senior Analyst',780000,'Banglore','N'),
	 ('Anita Banerjee','Analyst',674629,'Jaipur','Y'),
	 ('Prem Menon','Associate',1161030,'Banglore','Y'),
	 ('Ranjeet Kulkarni','Senior Associate',1744115,'Banglore','Y'),
	 ('Chinmay Gupta','Associate',968562,'Jaipur','Y'),
	 ('Rahul Kumar','Associate',1107472,'Banglore','Y'),
	 ('Abhijeet Nair','Analyst',570000,'Jaipur','Y'),
	 ('Chandan Bhatia','Associate',1096816,'Jaipur','Y'),
	 ('Hiral Mehta','Senior Analyst',747378,'Pune','N');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Barkha Reddy','Senior Analyst',784515,'Jaipur','Y'),
	 ('Radhika Sharma','Associate',1038994,'Banglore','Y'),
	 ('Akhil Sharma','Analyst',661872,'Jaipur','Y'),
	 ('Ketan Pillai','Analyst',689119,'Banglore','N'),
	 ('Harini Khanna','Analyst',679122,'Pune','Y'),
	 ('Jagadish Nair','Senior Associate',2119272,'Pune','Y'),
	 ('Mohini Joshi','Analyst',675832,'Banglore','Y'),
	 ('Akshay Kumar','Analyst',677326,'Jaipur','Y'),
	 ('Isha Singh','Associate',999847,'Pune','Y'),
	 ('Abhay Singh','Analyst',667696,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Naina Khanna','Analyst',657556,'Banglore','Y'),
	 ('Anil Pillai','Analyst',666688,'Jaipur','Y'),
	 ('Neeraj Dhillon','Senior Analyst',827191,'Banglore','Y'),
	 ('Lochana Singh','Analyst',570000,'Banglore','Y'),
	 ('Meena Sharma','Analyst',650999,'Banglore','Y'),
	 ('Nanda Pillai','Analyst',570000,'Banglore','Y'),
	 ('Manisha Banerjee','Analyst',570000,'Banglore','Y'),
	 ('Diya Rao','Analyst',570000,'Pune','Y'),
	 ('Kirti Rao','Analyst',570000,'Banglore','N'),
	 ('Malati Khanna','Analyst',689746,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Kavya Menon','Analyst',652764,'Banglore','N'),
	 ('Agni Chowdhury','Analyst',668447,'Jaipur','Y'),
	 ('Damini Verma','Manager',2910548,'Jaipur','Y'),
	 ('Amitabh Menon','Analyst',695121,'Jaipur','Y'),
	 ('Ishita Joshi','Associate',990176,'Pune','Y'),
	 ('Drishti Bhatia','Analyst',665297,'Pune','Y'),
	 ('Jayant Kulkarni','Analyst',570000,'Banglore','Y'),
	 ('Mayank Gupta','Analyst',570000,'Banglore','Y'),
	 ('Rakesh Menon','Manager',3287201,'Banglore','Y'),
	 ('Raj Verma','Associate',1479593,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Gita Kapoor','Analyst',570000,'Pune','N'),
	 ('Pratibha Verma','Senior Analyst',866178,'Banglore','Y'),
	 ('Jitendra Bhatia','Analyst',693467,'Banglore','Y'),
	 ('Balraj Singh','Senior Analyst',739278,'Jaipur','N'),
	 ('Dhaval Pillai','Analyst',688026,'Pune','Y'),
	 ('Leela Kumar','Analyst',570000,'Banglore','N'),
	 ('Ahana Banerjee','Analyst',570000,'Jaipur','Y'),
	 ('Mitra Singh','Analyst',570000,'Banglore','Y'),
	 ('Manav Pillai','Analyst',570000,'Banglore','Y'),
	 ('Ashok Chowdhury','Senior Analyst',831898,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Anjali Rao','Analyst',570000,'Jaipur','Y'),
	 ('Anand Sinha','Analyst',675379,'Jaipur','Y'),
	 ('Kamini Singh','Analyst',671736,'Banglore','Y'),
	 ('Pallavi Pillai','Senior Analyst',823585,'Banglore','Y'),
	 ('Kushan Dhillon','Analyst',699616,'Banglore','Y'),
	 ('Mahendra Iyer','Analyst',693026,'Banglore','Y'),
	 ('Rajat Reddy','Associate',1580928,'Banglore','Y'),
	 ('Jigar Rao','Analyst',570000,'Banglore','Y'),
	 ('Nikita Sharma','Senior Analyst',800000,'Banglore','N'),
	 ('Azad Kumar','Senior Analyst',874157,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Hema Banerjee','Senior Analyst',837838,'Pune','Y'),
	 ('Dhanya Kulkarni','Analyst',570000,'Pune','Y'),
	 ('Ranjana Sinha','Manager',2586435,'Banglore','Y'),
	 ('Ayush Patel','Senior Analyst',860479,'Jaipur','Y'),
	 ('Mohan Kapoor','Analyst',570000,'Banglore','Y'),
	 ('Mukesh Nair','Analyst',570000,'Banglore','N'),
	 ('Chitrangada Patel','Associate',1023034,'Jaipur','Y'),
	 ('Durga Kaur','Analyst',570000,'Pune','Y'),
	 ('Megha Patel','Analyst',570000,'Banglore','Y'),
	 ('Ayesha Sharma','Senior Analyst',797979,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Arnav Nair','Senior Analyst',759937,'Jaipur','Y'),
	 ('Gopal Nair','Analyst',570000,'Pune','Y'),
	 ('Priyanka Chowdhury','Associate',1370487,'Banglore','Y'),
	 ('Divya Banerjee','Analyst',694789,'Pune','Y'),
	 ('Purva Dhillon','Associate',1022523,'Banglore','Y'),
	 ('Bipin Chowdhury','Associate',950310,'Jaipur','Y'),
	 ('Dhruv Chowdhury','Analyst',570000,'Pune','Y'),
	 ('Prabhakar Gupta','Senior Analyst',878914,'Banglore','Y'),
	 ('Neha Mehta','Senior Analyst',803203,'Banglore','Y'),
	 ('Rajani Singh','Associate',1550000,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Prajwal Kumar','Senior Analyst',798506,'Banglore','Y'),
	 ('Rashmi Chowdhury','Senior Associate',2415447,'Banglore','Y'),
	 ('Gitanjali Joshi','Analyst',662617,'Pune','Y'),
	 ('Manjari Rao','Analyst',685966,'Banglore','Y'),
	 ('Parvati Rao','Senior Analyst',766540,'Banglore','Y'),
	 ('Aanya Sharma','Analyst',684097,'Jaipur','Y'),
	 ('Haritha Kulkarni','Senior Analyst',874620,'Pune','Y'),
	 ('Pratik Singh','Senior Analyst',894749,'Banglore','Y'),
	 ('Mansi Dhillon','Analyst',570000,'Banglore','N'),
	 ('Abishek Menon','Analyst',570000,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Lalit Gupta','Analyst',688925,'Banglore','Y'),
	 ('Nutan Khanna','Senior Analyst',757860,'Banglore','N'),
	 ('Arushi Khanna','Senior Analyst',731274,'Jaipur','Y'),
	 ('Ravindra Kaur','Senior Associate',2084629,'Banglore','Y'),
	 ('Amrita Khanna','Analyst',570000,'Jaipur','Y'),
	 ('Neela Bhatia','Senior Analyst',781187,'Banglore','Y'),
	 ('Rajni Iyer','Associate',1100000,'Banglore','N'),
	 ('Rajiv Nair','Associate',1364647,'Banglore','Y'),
	 ('Ratan Banerjee','Senior Associate',2078123,'Banglore','Y'),
	 ('Ishani Kapoor','Associate',1011693,'Pune','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Keshav Sinha','Analyst',660441,'Banglore','N'),
	 ('Priti Kulkarni','Associate',1171667,'Banglore','Y'),
	 ('Karan Reddy','Analyst',570000,'Banglore','Y'),
	 ('Bhavin Joshi','Senior Analyst',800808,'Jaipur','Y'),
	 ('Ashish Pillai','Senior Analyst',808913,'Jaipur','Y'),
	 ('Ankita Kaur','Analyst',570000,'Jaipur','Y'),
	 ('Naresh Rao','Analyst',669647,'Banglore','Y'),
	 ('Raghu Patel','Associate',1279950,'Banglore','Y'),
	 ('Gayatri Verma','Analyst',667714,'Pune','Y'),
	 ('Indrani Verma','Associate',1100000,'Pune','N');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Rhea Sharma','Senior Associate',1884348,'Banglore','Y'),
	 ('Anurag Kumar','Analyst',570000,'Jaipur','Y'),
	 ('Atharv Rao','Senior Analyst',850060,'Jaipur','N'),
	 ('Rachana Gupta','Associate',1150000,'Banglore','N'),
	 ('Alok Singh','Analyst',679088,'Jaipur','Y'),
	 ('Ishaan Reddy','Associate',901372,'Pune','Y'),
	 ('Harsha Pillai','Senior Analyst',743907,'Pune','N'),
	 ('Priya Pillai','Associate',1423630,'Banglore','Y'),
	 ('Nitin Iyer','Senior Analyst',822884,'Banglore','Y'),
	 ('Lakshmi Mehta','Analyst',570000,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Prutha Banerjee','Associate',1130975,'Banglore','Y'),
	 ('Kamal Verma','Analyst',570000,'Banglore','Y'),
	 ('Madhav Kapoor','Analyst',570000,'Banglore','Y'),
	 ('Ankit Bhatia','Analyst',682722,'Jaipur','Y'),
	 ('Bijay Khanna','Associate',958924,'Jaipur','Y'),
	 ('Kshitij Bhatia','Analyst',698795,'Banglore','Y'),
	 ('Nandini Chowdhury','Analyst',673115,'Banglore','Y'),
	 ('Ayaan Gupta','Senior Analyst',874505,'Jaipur','Y'),
	 ('Pratima Reddy','Senior Analyst',757280,'Banglore','N'),
	 ('Pankaj Chowdhury','Senior Analyst',885800,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Madhu Joshi','Analyst',681109,'Banglore','Y'),
	 ('Mahima Menon','Analyst',570000,'Banglore','Y'),
	 ('Amit Nair','Analyst',669794,'Jaipur','Y'),
	 ('Geetanjali Singh','Analyst',570000,'Pune','Y'),
	 ('Puneet Rao','Associate',1502831,'Banglore','Y'),
	 ('Kedar Khanna','Analyst',570000,'Banglore','Y'),
	 ('Bhavna Nair','Senior Analyst',881213,'Jaipur','Y'),
	 ('Mukul Menon','Analyst',570000,'Banglore','Y'),
	 ('Bikram Sinha','Associate',1020947,'Jaipur','Y'),
	 ('Amita Iyer','Analyst',570000,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Amar Kapoor','Analyst',687204,'Jaipur','Y'),
	 ('Aishwarya Rao','Analyst',696134,'Jaipur','Y'),
	 ('Bhavya Iyer','Senior Analyst',807821,'Jaipur','Y'),
	 ('Ajeet Kaur','Analyst',652519,'Jaipur','Y'),
	 ('Kavita Iyer','Analyst',570000,'Banglore','Y'),
	 ('Preity Iyer','Senior Analyst',749271,'Banglore','Y'),
	 ('Avni Mehta','Senior Analyst',813458,'Jaipur','Y'),
	 ('Abhiram Iyer','Analyst',695357,'Jaipur','Y'),
	 ('Narain Banerjee','Analyst',570000,'Banglore','N'),
	 ('Asha Kulkarni','Senior Analyst',808047,'Jaipur','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Abhinav Joshi','Analyst',570000,'Jaipur','Y'),
	 ('Advaita Kulkarni','Analyst',694539,'Jaipur','Y'),
	 ('Ananya Kulkarni','Analyst',570000,'Jaipur','Y'),
	 ('Hemant Rao','Senior Analyst',732142,'Pune','Y'),
	 ('Chetan Dhillon','Associate',917419,'Jaipur','Y'),
	 ('Pavan Bhatia','Senior Analyst',865555,'Banglore','N'),
	 ('Areen Kapoor','Analyst',570000,'Jaipur','Y'),
	 ('Kabir Dhillon','Analyst',570000,'Banglore','N'),
	 ('Parul Banerjee','Senior Analyst',753470,'Banglore','Y'),
	 ('Ila Sharma','Senior Analyst',805979,'Pune','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Manjeet Bhatia','Analyst',570000,'Banglore','Y'),
	 ('Aakash Patel','Analyst',570000,'Jaipur','Y'),
	 ('Rekha Mehta','Senior Associate',2121197,'Banglore','Y'),
	 ('Prachi Sharma','Senior Analyst',816659,'Banglore','Y'),
	 ('Rashi Pillai','Senior Associate',2295146,'Banglore','Y'),
	 ('Aditya Sinha','Analyst',570000,'Jaipur','Y'),
	 ('Avani Kaur','Senior Analyst',813559,'Jaipur','Y'),
	 ('Padma Kulkarni','Senior Analyst',879923,'Banglore','Y'),
	 ('Aarav Gupta','Analyst',570000,'Jaipur','Y'),
	 ('Harish Sinha','Analyst',570000,'Pune','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Karthik Kapoor','Analyst',660243,'Banglore','Y'),
	 ('Maruti Mehta','Analyst',693416,'Banglore','Y'),
	 ('Fathima Sharma','Analyst',570000,'Pune','Y'),
	 ('Nitara Joshi','Senior Analyst',754564,'Banglore','Y'),
	 ('Nikhil Gupta','Senior Analyst',856722,'Banglore','Y'),
	 ('Darshan Singh','Manager',3039209,'Jaipur','Y'),
	 ('Purab Kaur','Associate',1137127,'Banglore','Y'),
	 ('Jaya Sinha','Analyst',657432,'Banglore','Y'),
	 ('Jayanti Pillai','Analyst',672615,'Banglore','Y'),
	 ('Gautam Patel','Analyst',686097,'Pune','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Manas Sinha','Analyst',570000,'Banglore','N'),
	 ('Lavanya Patel','Analyst',659554,'Banglore','Y'),
	 ('Brinda Banerjee','Associate',1019658,'Jaipur','Y'),
	 ('Arundhati Menon','Senior Analyst',841886,'Jaipur','Y'),
	 ('Advika Pillai','Analyst',570000,'Jaipur','Y'),
	 ('Akshara Patel','Analyst',570000,'Jaipur','Y'),
	 ('Anuradha Patel','Analyst',654800,'Jaipur','Y'),
	 ('Chaitanya Rao','Associate',1031403,'Jaipur','Y'),
	 ('Nisha Singh','Senior Analyst',842589,'Banglore','Y'),
	 ('Neelam Kaur','Senior Analyst',771600,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Jhanvi Banerjee','Analyst',689961,'Banglore','Y'),
	 ('Aravind Singh','Analyst',570000,'Jaipur','Y'),
	 ('Jaidev Khanna','Manager',2945176,'Pune','Y'),
	 ('Chirag Sharma','Associate',1007064,'Jaipur','Y'),
	 ('Mitali Reddy','Analyst',664724,'Banglore','Y'),
	 ('Ketaki Kulkarni','Analyst',570000,'Banglore','Y'),
	 ('Jahnavi Iyer','Senior Associate',1729701,'Pune','Y'),
	 ('Pradnya Patel','Senior Analyst',882632,'Banglore','Y'),
	 ('Khushi Chowdhury','Analyst',570000,'Banglore','Y'),
	 ('Preethi Nair','Senior Analyst',828900,'Banglore','Y');
INSERT INTO public.employee_data ("Name","Role","CurrentComp","Location","Active") VALUES
	 ('Pushpa Mehta','Associate',1030381,'Banglore','Y'),
	 ('Ajay Bhatia','Analyst',570000,'Jaipur','Y'),
	 ('Deepak Kapoor','Senior Associate',1714061,'Jaipur','Y'),
	 ('Dhairya Khanna','Senior Associate',1402414,'Jaipur','Y'),
	 ('Dhanush Sinha','Senior Associate',1402414,'Jaipur','Y'),
	 ('Devi Menon','Senior Associate',1714061,'Jaipur','Y'),
	 ('Deepali Joshi','Senior Associate',1324502,'Jaipur','Y'),
	 ('Devang Iyer','Senior Associate',1869885,'Jaipur','Y'),
	 ('Deepa Reddy','Senior Associate',1324502,'Jaipur','Y'),
	 ('Deepika Nair','Senior Associate',1542655,'Jaipur','Y');
