INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Jaipur','1-2'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Jaipur','0-1'),
	 ('Associate','Jaipur','3-4'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Pune','2-3'),
	 ('Senior Analyst','Pune','2-3');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Pune','0-1'),
	 ('Senior Associate','Pune','6-7'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Jaipur','1-2'),
	 ('Senir Associate','Jaipur','1-2'),
	 ('Analyst','Pune','');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Banglore','3-4'),
	 ('Associate','Jaipur','4-5'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Associate','Banglore','5-6'),
	 ('Analyst','Banglore','0-1'),
	 ('Associate','Jaipur','4-5');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Pune','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Jaipur','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Jaipur','0-1'),
	 ('Associate','Banglore','3-4'),
	 ('Associate','Banglore','4-5'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Associate','Jaipur','4-5'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Banglore','2-3');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senir Associate','Jaipur',''),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Associate','Banglore','4-5'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Associate','Banglore','5-6'),
	 ('Analyst','Pune','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Senir Associate','Jaipur','');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Associate','Banglore','5-6'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Pune','2-3'),
	 ('Analyst','Jaipur','1-2'),
	 ('Senior Associate','Banglore','6-7'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Jaipur','1-2');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Jaipur','1-2'),
	 ('Senior Analyst','Banglore','1-2'),
	 ('Associate','Pune','3-4'),
	 ('Senior Analyst','Pune','1-2'),
	 ('Analyst','Banglore','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Jaipur','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Associate','Pune','2-3'),
	 ('Manager','Banglore','8-9'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','0-1'),
	 ('Associate','Banglore','4-5'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Pune','2-3');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Jaipur','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Jaipur','1-2'),
	 ('Associate','Banglore','2-3'),
	 ('Senior Associate','Banglore','4-5'),
	 ('Associate','Jaipur','3-4'),
	 ('Associate','Banglore','4-5');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Jaipur','0-1'),
	 ('Associate','Jaipur','4-5'),
	 ('Senior Analyst','Pune','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Associate','Banglore','4-5'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Pune','1-2'),
	 ('Senior Associate','Pune','4-5'),
	 ('Analyst','Banglore','1-2');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Jaipur','1-2'),
	 ('Associate','Pune','3-4'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Jaipur','1-2'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Pune','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Jaipur','1-2'),
	 ('Manager','Jaipur','7-8'),
	 ('Analyst','Jaipur','1-2'),
	 ('Associate','Pune','4-5'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Banglore','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Banglore','0-1'),
	 ('Manager','Banglore','9-10'),
	 ('Associate','Banglore','3-4'),
	 ('Analyst','Pune','0-1'),
	 ('Senior Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Jaipur','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Jaipur','1-2'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Associate','Banglore','3-4');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Jaipur','1-2'),
	 ('Senior Analyst','Pune','2-3'),
	 ('Analyst','Pune','0-1'),
	 ('Manager','Banglore','9-10'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Associate','Jaipur','3-4');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Pune','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Pune','0-1'),
	 ('Associate','Banglore','3-4'),
	 ('Analyst','Pune','1-2'),
	 ('Associate','Banglore','3-4'),
	 ('Associate','Jaipur','3-4'),
	 ('Analyst','Pune','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Associate','Banglore','4-5'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Associate','Banglore','6-7'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Jaipur','1-2'),
	 ('Senior Analyst','Pune','2-3');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Associate','Banglore','4-5'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Associate','Banglore','4-5');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Banglore','4-5'),
	 ('Senior Associate','Banglore','4-5'),
	 ('Associate','Pune','3-4'),
	 ('Analyst','Banglore','1-2'),
	 ('Associate','Banglore','3-4'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Banglore','1-2');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Banglore','3-4'),
	 ('Analyst','Pune','1-2'),
	 ('Associate','Pune','4-5'),
	 ('Senior Associate','Banglore','6-7'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Associate','Banglore','3-4'),
	 ('Analyst','Jaipur','1-2'),
	 ('Associate','Pune','4-5'),
	 ('Senior Analyst','Pune','2-3');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senir Associate','Jaipur',''),
	 ('Associate','Banglore','4-5'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Associate','Banglore','4-5'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Associate','Jaipur','3-4'),
	 ('Analyst','Banglore','1-2');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Banglore','1-2'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Senir Associate','Jaipur',''),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Pune','0-1'),
	 ('Associate','Banglore','3-4');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Associate','Jaipur','4-5'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Jaipur','1-2'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Banglore','1-2'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senir Associate','Jaipur',''),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Analyst','Pune','2-3');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Jaipur','3-4'),
	 ('Senir Associate','Jaipur',''),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Pune','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Associate','Banglore','6-7');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Associate','Banglore','5-6'),
	 ('Analyst','Jaipur','0-1'),
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Pune','0-1'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Pune','0-1');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Manager','Jaipur','8-9'),
	 ('Associate','Banglore','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Pune','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Analyst','Banglore','1-2'),
	 ('Associate','Jaipur','4-5');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Senior Analyst','Jaipur','2-3'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','0-1'),
	 ('Analyst','Jaipur','1-2'),
	 ('Associate','Jaipur','3-4'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Jaipur','0-1'),
	 ('Manager','Pune','8-9');
INSERT INTO public.groupbyexperience ("Role","Location","Years of Experience") VALUES
	 ('Associate','Jaipur','4-5'),
	 ('Senir Associate','Jaipur',''),
	 ('Analyst','Banglore','1-2'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Associate','Pune','5-6'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Analyst','Banglore','0-1'),
	 ('Senior Analyst','Banglore','2-3'),
	 ('Associate','Banglore','4-5'),
	 ('Analyst','Jaipur','0-1');
